create new addOption function in AbstractQuery
Ang3/php-odoo-api-client pull request #15
Opened 2021-07-27 14:59 UTC by JeuFore

I created an addOption function because, setOptions overrides all previous options. For example a select ['id,' name'].

2021-07-28 08:10 UTC, JeuFore commented
This is for issue #12

2021-07-29 15:04 UTC, Agrege requested changes
Hi,
Thank you for you pull request.
Can you remove the type hint for **$value** and add phpdoc for this param with type "**mixed**"?

2021-08-02 06:41 UTC, Wilders commented
On fc4094ee89d267a83b8f68b516ebee9e91a8badc
Usage of "mixed" requires PHP > 8.0.0, just delete the type hint
https://www.php.net/manual/en/language.types.declarations.php

2021-08-14 11:42 UTC, merged

2021-08-18 09:18 UTC, Wilders commented
Hi @Ang3, Could you make a release so the package is also updated on packagist ?

Thanks ! 😄

2021-08-18 12:03 UTC, Ang3 commented
Yep, sry I'm little busy but many updates on September.
Release done! ;)